### ISSUE TITLE
collaborate with other guzzle bundles?

### ISSUE THREAD

**Issue by lsmith77** [misd-service-development/guzzle-bundle#28]
https://github.com/search?q=Guzzle+Bundle&ref=searchresults&type=Repositories

would be great if there could be some work to collaborate and build one GuzzleBundle instead of the current long list.

/cc @zachbadgett @ddeboer @thewilkybarkid @ludofleury @xamado

**Comment by ghost** [comment]
Please look at issue #90

**Comment by Tobion** [comment]
@lsmith77 IMO this issue can be closed. The many-bundle problem still persists but this place is the wrong repo to possibly discuss this as it is not maintained and only for Guzzle 3.

**Comment by Tobion** [comment]
@lsmith77 please close
