### ISSUE TITLE
Warning: file_get_contents(~/vendor/misd/guzzle-bundle/Misd/GuzzleBundle/Resources/views/Collector/guzzle.html.twig): failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by lsv** [misd-service-development/guzzle-bundle#75]
symfony/symfony v2.6.0 645bb3248db50d653d18929eb0c92b131b4f35ad
misd/guzzle-bundle v1.1.5 555c105ef4ac66597a029fe634dee0fe4f9cb084

When I open any page I get this error

![screenshot from 2014-12-03 08 37 36](https://cloud.githubusercontent.com/assets/20708/5277197/e5680c64-7ac7-11e4-84a1-ec530ed17227.png)

In the profiler I get this error

```
Warning: file_get_contents(~/vendor/misd/guzzle-bundle/Misd/GuzzleBundle/Resources/views/Collector/guzzle.html.twig): failed to open stream: No such file or directory
```

Now what I can see is that the directory for the view is wrong, should be

```
~/vendor/misd/guzzle-bundle/Resources/views/Collector/guzzle.html.twig
```

**Comment by stanivanovpro** [comment]
Just had the same issues with Symfony 2.7 and I can confirm clearing cache (even if you're on dev environment) fixes this. Seems it happens after vendors are updated.
